### ISSUE TITLE
the hub doesnt reboot into the LeDe

### ISSUE THREAD

**Issue by fahadshery** [mkresin/lede#3]
Did the following steps:
1-Open the `.asc file` with Notepad++, select all and copy
Goto the Putty console window and right click (should still be open and connected to the router). The asc file will transfer and execute.
2-`tftpboot 0x81000000 lede-lantiq-xrx200-BTHOMEHUBV5A-installimage.bin; bootm 0x81000000`
3- Press enter key to start Lede installation
4- `nanddump --file /tmp/mounts/USB-A1/hh5a.nanddump /dev/mtd4`
5- `prepare`
6- ` sysupgrade /tmp/mounts/USB-A1/lede-lantiq-xrx200-BTHOMEHUBV5A-squashfs-sysupgrade.bin`
7-  power off/on when see the UART again.

this doesn't start router into Luci and default hub firmware still there
Am i missing something?

Here is the log:
[(https://pastebin.com/rG0q9pTi)]

**Comment by mkresin** [comment]
The prepare script expects you to type YESIHAVEABACKUP  (YESIHAVE ___A___ BACKUP). But you typed YESIHAVEBACKUP without the extra A.

**Comment by fahadshery** [comment]
Apologies, my mistake. But when loaded LuCI, I can't seem to find wireless settings. How do I enable wireless interface on the router? I can't locate the file /etc/config/wireless either

**Comment by fahadshery** [comment]
here is the version:  Reboot (17.01.4, r3560-79f57e422d)
