### ISSUE TITLE
Won,t install!

### ISSUE THREAD

**Issue by morosanu22** [mkresin/lede#4]
Everytime when i'm trying to install the firmware from usb i get this error!  Tried vith different versions of lede for BT HH5a

Starting installation...
TRYING to decrypt u-boot env with key B1D3B4BD0970FCA9261E23C2170DB8E52407C71DAC06098678C0885BC7E68CCD
TRYING to decrypt u-boot env with key 86fd5557bab554172a97eaec65680745d4ec2efe723decb956a50bd9bc13e1a8
TRYING to decrypt u-boot env with key 3E4CA8114D15BFC653B2BF9519EF2B94200E30345503B125C1D0BE776698B950
SUCCESSFULLY decrypted u-boot env
ERROR bootcmd_openrg already exists. Please restore backup and start again

**Comment by mkresin** [comment]
Obviously your installation failed at some point and you re-run the <strike>installation</strike> prepare script to try again.

The <strike>installer</strike> prepare script notices that parts of the modification are already done and stops to proceed. So far everything works as expected.

The <strike>installer</strike> prepare script even tells you what to do prior to run the script again:

> Please restore backup and start again

Follow the advice and it will most likely work.

**Comment by mkresin** [comment]
If you have successfully prepared the HomeHub 5a, you can run the command shown after the successful preparation:

```
Preparation completed!

Your attached USB media is mounted as a subdirectory at /tmp/mounts/

To install LEDE, run:

  sysupgrade /tmp/mounts/<directory>/lede-17.01.4-lantiq-xrx200-BTHOMEHUBV5A-squashfs-sysupgrade.bin

Sysupgrade will automatically restart your device when it has finished.
If the CFG-04 UART prompt appears, power-cycle your device!
The hub should now boot up using LEDE.
```

**Comment by morosanu22** [comment]
I tried with sysupgrade but i'm getting this: 

root@LEDE:/# sysupgrade /tmp/mounts/USB-A/lede-17.01.4-lantiq-xrx200-BTHOMEHUBV5
A-squashfs-sysupgrade
Image metadata not found
Use sysupgrade -F to override this check when downgrading or flashing to vendor                                                        firmware
Image check 'fwtool_check_image' failed.

**Comment by morosanu22** [comment]
root@LEDE:/# sysupgrade /tmp/mounts/USB-A1/lede-17.01.4-lantiq-xrx200-BTHOMEHUBV
5A-squashfs-sysupgrade
[  364.234404] [EXFAT] trying to mount...
[  364.684113] [EXFAT] mounted successfully
Image metadata not found
Use sysupgrade -F to override this check when downgrading or flashing to vendor firmware
Image check 'fwtool_check_image' failed.
root@LEDE:/#

**Comment by mkresin** [comment]
Please try an openwrt 18.06 image.
